### ISSUE TITLE
Gather github accounts for sharing priviliges

### ISSUE THREAD

**Issue by michalvankodev** [michalvankodev/ness-inter-poll#2]
Hi everyone,
I will need your github account name so I can give you permission to push code into this repository.

Please comment under this issue.

**Comment by JaroslavaJaskova** [comment]
Hi Michal :)

**Comment by maroskutschy** [comment]
Hello, this is Maros :)

**Comment by LukasOscipovsky** [comment]
Hello :)

**Comment by KyptoDaydream** [comment]
holla

**Comment by TLojka** [comment]
Hi
