### ISSUE TITLE
Write down use cases

### ISSUE THREAD

**Issue by michalvankodev** [michalvankodev/ness-inter-poll#3]
As we are going to prepare for a planning session we will need to create a list of use cases which will then serve as a foundation for UI design.

**Comment by JaroslavaJaskova** [comment]
Use cases for Poll/Survey creator added into document
[Ness-inter-poll_SRS_v02.docx](https://github.com/michalvankodev/ness-inter-poll/files/1652956/Ness-inter-poll_SRS_v02.docx)

**Comment by JaroslavaJaskova** [comment]
Use cases for Poll/Survey voter added into document
[Ness-inter-poll_SRS_v03.docx](https://github.com/michalvankodev/ness-inter-poll/files/1654862/Ness-inter-poll_SRS_v03.docx)

**Comment by michalvankodev** [comment]
Hi @JaroslavaJaskova,
Awesome job, I really like the structure of the document and the use cases for publishers.

I have few notes:
- We should rename _users_ which are able to CREATE, UPDATE, DELETE and PUBLISH - to _Publishers_.

-  > User is able to vote on poll except of his own poll.
    - I don't think this should restricted.

- > List of created Polls/Surveys. Each selected Poll/Survey can be edited, deleted, grouped, published
    - Do you have an idea how these are going to be grouped?

- > Answer field can be added under (max?)
   - I don't think we would need to have a max number. There are lot of options for various questions.

I have some use cases for administrator which would be cool to include in the document: 

            3.1.9 Administrator control Users
Administrator is able to see list of users with their permissions and is able to see their contribution.
Administrator is able to modify users information, permissions and reset their password.
Administrator is able to delete users.
Administrator is able to modify or delete all polls/surveys.

Please review and if you are able to include those in the document please do.
Don't forget to upload the document to the git repository so we can show it on our next meetup ;)

Thank you very much.

**Comment by LukasOscipovsky** [comment]
Hi All,
Awesome described. From my side only one question/suggestion. One report is report of filled poll/survey of one user or display graphically stats of poll/survey of answered questions. There is no need to know how the specific user has answered the poll/survey.
Otherwise looks pretty good.
Thanks
Lukas

**Comment by JaroslavaJaskova** [comment]
Hi guys,
@michalvankodev thank you for reviewing! I will include your comments into document asap. Regarding grouping of poll/surveys - that should be custom groups created by publisher on home page based on his preferences to group stuff by topic, dates, whatever else..I will include to document also, ok?
@LukasOscipovsky, regarding report stuff I meant graphical stats :) Thank you for pointing out..

Have a nice day,
Jarka

**Comment by maroskutschy** [comment]
Hi Jarka,
very nice use cases description, great job, thanks.
I think it covers all use cases.
Have a nice day 
Regards
Maros

**Comment by JaroslavaJaskova** [comment]
Hi Maros,
thank you for your feedback :)
Jarka

**Comment by JaroslavaJaskova** [comment]
Hi Maros,
thank you for your feedback! :)
Jarka

**Comment by JaroslavaJaskova** [comment]
Notes incorporated...
[Ness-inter-poll_SRS_v04.docx](https://github.com/michalvankodev/ness-inter-poll/files/1674001/Ness-inter-poll_SRS_v04.docx)

**Comment by JaroslavaJaskova** [comment]
Reduced Use Cases
[Ness-inter-poll_SRS_v05.docx](https://github.com/michalvankodev/ness-inter-poll/files/1684616/Ness-inter-poll_SRS_v05.docx)

**Comment by JaroslavaJaskova** [comment]
Last version added
[NessInterPollUseCasesTable.docx](https://github.com/michalvankodev/ness-inter-poll/files/1706133/NessInterPollUseCasesTable.docx)

**Comment by michalvankodev** [comment]
Please commit these changes to the repo. :)
